name: Deploy to Production

env:
    CONTEXT_DIR: './'
    IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/production
    DOCKERFILE: Dockerfile
    CAPROVER_APP: tims-backend
    DOCKER_REGISTRY: docker.io

on:
    push:
        branches:
            - main

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: |
                  echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME" >> $GITHUB_ENV
                  export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME
                  echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$GITHUB_SHA-gitsha" >> $GITHUB_ENV
            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }} 
                  password: ${{ secrets.DOCKER_TOKEN }}
            - name: Build and Push Release to DockerHub
              shell: bash
              run: ./build_and_push.sh
            - name: Deploy to CapRover
              uses: caprover/deploy-from-github@main
              with:
                  server: ${{ secrets.CAPROVER_SERVER }}
                  app: ${{ secrets.APP_NAME }}
                  token: '${{ secrets.APP_TOKEN }}'
                  image: '${{ env.FULL_IMAGE_NAME }}'
